### ISSUE TITLE
Issue when upgrading minio bosh release

### ISSUE THREAD

**Issue by shaun7pan** [minio/minio-boshrelease#42] opened 2018-02-02 04:27 UTC
Hi Team,

Greetings. We are having 4 nodes minio distributed cluster installed using bosh v1. now we are facing issue when upgrading minio bosh release from 2017-11-22T19-55-46 to 2018-01-18T20-33-21Z. Error message is shown as below. There is no issue if we do fresh bosh deploy directly. 

The bosh version we are using is `BOSH 1.3262.26.0`
```
#vi /var/vcap/sys/log/minio-server/minio-server.stdout.log
Status:         4 Online, 0 Offline. We can withstand [2] drive failure(s).
Configuration file /var/vcap/store/minio-config/config.json migrated from version '20' to '21' successfully.
Configuration file /var/vcap/store/minio-config/config.json migrated from version '21' to '22' successfully.

Trace: 1: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:221:cmd.serverMain()
       2: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499:cli.HandleAction()
       3: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214:cli.Command.Run()
       4: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260:cli.(*App).Run()
       5: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/main.go:149:cmd.Main()
       6: /q/.q/sources/gopath/src/github.com/minio/minio/main.go:71:main.main()
[2018-02-02T04:13:50.42969346Z] [ERROR] Initializing object layer failed **(Http://192.168.33.18:9001/Var/Vcap/Store/Minio-Server: Server Versions Do Not Match)**

Trace: 1: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:221:cmd.serverMain()
       2: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499:cli.HandleAction()
       3: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214:cli.Command.Run()
       4: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260:cli.(*App).Run()
       5: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/main.go:149:cmd.Main()
       6: /q/.q/sources/gopath/src/github.com/minio/minio/main.go:71:main.main()
[2018-02-02T04:14:20.515044968Z] [ERROR] Initializing object layer failed **(Http://192.168.33.18:9001/Var/Vcap/Store/Minio-Server: Server Versions Do Not Match)**

Trace: 1: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:221:cmd.serverMain()
       2: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499:cli.HandleAction()
       3: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214:cli.Command.Run()
       4: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260:cli.(*App).Run()
       5: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/main.go:149:cmd.Main()
       6: /q/.q/sources/gopath/src/github.com/minio/minio/main.go:71:main.main()
[2018-02-02T04:15:00.593545493Z] [ERROR] Initializing object layer failed **(Http://192.168.33.18:9001/Var/Vcap/Store/Minio-Server: Server Versions Do Not Match)**

Trace: 1: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:221:cmd.serverMain()
       2: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499:cli.HandleAction()
       3: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214:cli.Command.Run()
       4: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260:cli.(*App).Run()
       5: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/main.go:149:cmd.Main()
       6: /q/.q/sources/gopath/src/github.com/minio/minio/main.go:71:main.main()
[2018-02-02T04:15:40.677619016Z] [ERROR] Initializing object layer failed **(Http://192.168.33.18:9001/Var/Vcap/Store/Minio-Server: Server Versions Do Not Match)**

Trace: 1: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:221:cmd.serverMain()
       2: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499:cli.HandleAction()
       3: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214:cli.Command.Run()
       4: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260:cli.(*App).Run()
       5: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/main.go:149:cmd.Main()
       6: /q/.q/sources/gopath/src/github.com/minio/minio/main.go:71:main.main()
[2018-02-02T04:16:20.76092082Z] [ERROR] Initializing object layer failed **(Http://192.168.33.18:9001/Var/Vcap/Store/Minio-Server: Server Versions Do Not Match)**
```

**Comment by krishnasrinivas** [comment] 2018-02-02 05:06
@shaun7pan thanks for reporting, we are taking a look.

**Comment by krishnasrinivas** [comment] 2018-02-02 05:07
@shaun7pan Does the server come up after sometime? Or does the minio server never comes up?

**Comment by shaun7pan** [comment] 2018-02-02 05:14
No, the error result in server stuck in `failing` state. We try to bring it back through `bosh cck` but never succeed.

**Comment by krishnasrinivas** [comment] 2018-02-02 05:21
Looks like bosh rolling upgrade does not happen till the first server comes up. Can you ssh into all the machines and issue `reboot`?

**Comment by shaun7pan** [comment] 2018-02-02 06:28
try to run `monit start` get the same error.
```
# monit status
The Monit daemon 5.2.5 uptime: 13m

Process 'minio-server'
  status                            Execution failed
  monitoring status                 monitored
  data collected                    Fri Feb  2 06:26:03 2018

System 'system_localhost'
  status                            running
  monitoring status                 monitored
  load average                      [0.04] [0.01] [0.00]
  cpu                               0.0%us 0.0%sy 0.0%wa
  memory usage                      110456 kB [1.3%]
  swap usage                        0 kB [0.0%]
  data collected                    Fri Feb  2 06:26:03 2018
```

```
# monit start minio-server
# cat /var/vcap/sys/log/minio-server/minio-server.stdout.log
Trace: 1: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:221:cmd.serverMain()
       2: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499:cli.HandleAction()
       3: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214:cli.Command.Run()
       4: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260:cli.(*App).Run()
       5: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/main.go:149:cmd.Main()
       6: /q/.q/sources/gopath/src/github.com/minio/minio/main.go:71:main.main()
[2018-02-02T06:26:13.920926855Z] [ERROR] Initializing object layer failed (Http://192.168.33.18:9001/Var/Vcap/Store/Minio-Server: Server Versions Do Not Match)
```

**Comment by krishnasrinivas** [comment] 2018-02-02 06:52
did you reboot the servers? is this your production setup? or can it be fixed later?

**Comment by shaun7pan** [comment] 2018-02-02 06:58
I did reboot as well but the same error happened.  This is our lab minio cluster server.

**Comment by krishnasrinivas** [comment] 2018-02-02 07:04
> This is our lab minio cluster server.

:+1: I am assuming it's a test setup then.

A workaround to fix the problem is, ssh into the servers where old binary is running and replace `/var/vcap/packages/minio/minio` with latest minio binary (https://dl.minio.io/server/minio/release/linux-amd64/) And then kill the minio process (kill -9 PID) and allow the monit to start the process again. That should fix it for now.

**Comment by krishnasrinivas** [comment] 2018-02-02 07:10
Do not forget to chmod +x minio after downloading

**Comment by shaun7pan** [comment] 2018-02-02 09:54
@krishnasrinivas Thanks a lot for your support. It fixed the issue. Just update what I have done here for the reference.

1. Manually download the binary to the other 3 nodes under the path `/var/vcap/packages/minio/minio` and `chmod +x minio` (the first node binary had already been updated during the bosh upgrade deployment failure)

2. SSH into each node and do `monit stop minio-server`. Confirm the process had been shutdown by running `ps -ef | grep minio`
3. Run `monit start minio-server` one by one on each node.
4. Confirm status by doing `monit status` on each node and also verify vm status through `bosh vms`, should be all running.
5. Do bosh deployment again using new release and it will clean bosh environment.

**Comment by krishnasrinivas** [comment] 2018-02-15 00:15
Fixed in the latest release. https://github.com/minio/minio-boshrelease/pull/43

**Closed by krishnasrinivas** 2018-02-15 00:15 UTC
